# Generated by Django 4.1.3 on 2022-12-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneysys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
